name: Docker CI

on:
  workflow_call:
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: gamerscorehub

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

#      - name: Build and push Docker Images
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file:
#          tags: iviscd/gamerscorehub:${{github.sha}}
#          push: true