name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build MySQL Container
        run: docker-compose build

      - name: Create MySQL Container
        run: docker-compose up -d

      - name: Wait for MySQL to be ready
        run: |
          until docker exec gsh-db mysqladmin ping -hlocalhost -uroot -proot; do
            echo "Waiting for MySQL to start..."
            sleep 20
          done

      - name: Create Databases
        run: |
          docker exec gsh-db mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS dbgamerscore;"
          docker exec gsh-db mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS dbgamerscoretest;"

      - name: Test with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn clean install